# Generated by Django 6.0.4 on 2026-05-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('activity_type', models.CharField(choices=[('event', 'Event'), ('meeting', 'Meeting'), ('task', 'Task'), ('log_call', 'Log Call')], max_length=20, verbose_name='Activity Type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Related To')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on Someone'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], default='pending', max_length=20, verbose_name='Status')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='All Day')),
                ('task_priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50, null=True, verbose_name='Priority')),
                ('due_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Recipient Email')),
                ('call_duration_display', models.CharField(blank=True, max_length=20, null=True, verbose_name='Call Duration')),
                ('call_duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Call Duration (Seconds)')),
                ('call_type', models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=50, null=True, verbose_name='Call Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('google_event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Google Calendar Event ID')),
                ('call_purpose', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call Purpose')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
