# Generated by Django 6.0.4 on 2026-05-11 07:19

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='activity',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('activity_related_models'), null=True, on_delete=django.db.models.deletion.CASCADE, to='core.horillacontenttype', verbose_name='Related Content Type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='activity',
            name='meeting_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_activities', to=settings.AUTH_USER_MODEL, verbose_name='Meeting Host'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Activity Owner'),
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='activity_participants', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activity_ac_activit_b6e897_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_at'], name='activity_ac_created_6c38cf_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='activity_ac_status_f471b6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['start_datetime'], name='activity_ac_start_d_185f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['due_datetime'], name='activity_ac_due_dat_548f68_idx'),
        ),
    ]
