# Generated by Django 6.0.4 on 2026-05-11 07:19

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalcondition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='approvalcondition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='approvalcondition',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('approval_models'), on_delete=django.db.models.deletion.CASCADE, related_name='approval_instances', to='core.horillacontenttype'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalinstance'),
        ),
        migrations.AddField(
            model_name='approvalprocessrule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='approvalprocessrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='approvalprocessrule',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='approvalcondition',
            name='approval_process_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='approvals.approvalprocessrule', verbose_name='Process rule'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='model',
            field=models.ForeignKey(help_text='Model this process applies to.', limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('approval_models'), on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='core.horillacontenttype', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='approvalprocessrule',
            name='approval_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_rules', to='approvals.approvalrule', verbose_name='Approval process'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approvals.approvalrule', verbose_name='Rule'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approval_process_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalprocessrule'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='approvalinstance',
            name='current_step',
            field=models.ForeignKey(blank=True, help_text='The step currently awaiting decision, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='approvals.approvalstep'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalstep'),
        ),
        migrations.AddConstraint(
            model_name='approvalprocessrule',
            constraint=models.UniqueConstraint(fields=('approval_process', 'order'), name='approvals_processrule_process_order_uniq'),
        ),
        migrations.AddIndex(
            model_name='approvalinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='approvals_a_content_03463d_idx'),
        ),
    ]
