# Generated by Django 6.0.4 on 2026-05-11 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Forecast Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('forecast_type', models.CharField(choices=[('deal_revenue_amount', 'Deal Revenue Amount'), ('deal_revenue_expected_amount', 'Deal Revenue Expected Amount'), ('deal_quantity', 'Deal Quantity')], default='deal_revenue_amount', max_length=50, verbose_name='Forecast Type')),
                ('include_pipeline', models.BooleanField(default=True, verbose_name='Include Pipeline')),
                ('include_best_case', models.BooleanField(default=True, verbose_name='Include Best Case')),
                ('include_commit', models.BooleanField(default=True, verbose_name='Include Commit')),
                ('include_closed', models.BooleanField(default=True, verbose_name='Include Closed')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Forecast Type',
                'verbose_name_plural': 'Forecast Types',
            },
        ),
        migrations.CreateModel(
            name='ForecastTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target amount (revenue or quantity)', max_digits=18, verbose_name='Target')),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, INR)', max_length=3, verbose_name='Currency')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, help_text='Current achieved amount (auto-calculated)', max_digits=18, verbose_name='Current Achievement')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_targets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned User')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_targets', to='core.period', verbose_name='Forecast Period')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_targets', to='core.role', verbose_name='Role')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('forcasts_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_targets', to='forecast.forecasttype', verbose_name='Forecast Type')),
            ],
            options={
                'verbose_name': 'Forecast Target',
                'verbose_name_plural': 'Forecast Targets',
                'ordering': ['-created_at'],
                'unique_together': {('assigned_to', 'period', 'forcasts_type')},
            },
        ),
        migrations.CreateModel(
            name='ForecastCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('forecast_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='forecast.forecasttype', verbose_name='Forecast Type')),
            ],
            options={
                'verbose_name': 'Forecast Condition',
                'verbose_name_plural': 'Forecast Conditions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Forecast Name')),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Target Amount')),
                ('pipeline_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Pipeline Amount')),
                ('best_case_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Best Case Amount')),
                ('commit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Commit Amount')),
                ('closed_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Closed Amount')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Actual Amount')),
                ('target_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Target Quantity')),
                ('pipeline_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Pipeline Quantity')),
                ('best_case_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Best Case Quantity')),
                ('commit_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Commit Quantity')),
                ('closed_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Closed Quantity')),
                ('actual_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Actual Quantity')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_forecasts', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fiscalyearinstance', verbose_name='Fiscal Year')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Forecast Owner')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.period', verbose_name='Period')),
                ('quarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quarter', verbose_name='Quarter')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('forecast_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.forecasttype', verbose_name='Forecast Type')),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastTargetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, help_text='Individual revenue target for this user', max_digits=18, verbose_name='User Revenue Target')),
                ('quantity_target', models.IntegerField(default=0, help_text='Individual quantity target for this user', verbose_name='User Quantity Target')),
                ('current_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Current achieved revenue for this user', max_digits=18, verbose_name='Current Revenue Achieved')),
                ('current_quantity', models.IntegerField(default=0, help_text='Current achieved quantity for this user', verbose_name='Current Quantity Achieved')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('forecast_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_targets', to='forecast.forecasttarget', verbose_name='Forecast Target')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_forecast_targets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Forecast Target User',
                'verbose_name_plural': 'Forecast Target Users',
                'unique_together': {('forecast_target', 'user')},
            },
        ),
    ]
