# Generated by Django 6.0.4 on 2026-05-11 07:19

import django.db.models.deletion
import horilla.contrib.duplicates.methods
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('action_on_create', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block')], default='allow', max_length=20, verbose_name='Action on Create')),
                ('action_on_edit', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block')], default='allow', max_length=20, verbose_name='Action on Edit')),
                ('alert_title', models.CharField(default='Potential Duplicate Detected', help_text='Title shown in the alert dialog', max_length=255, verbose_name='Alert Title')),
                ('alert_message', models.TextField(default='Similar records found. Do you want to proceed?', help_text='Message to show in alert when duplicates are detected', verbose_name='Alert Message')),
                ('show_duplicate_records', models.BooleanField(default=True, help_text='Show list of potential duplicates in the alert', verbose_name='Show Duplicate Records')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(help_text='The model this duplicate rule applies to', limit_choices_to=horilla.contrib.duplicates.methods.limit_content_types, on_delete=django.db.models.deletion.CASCADE, to='core.horillacontenttype', verbose_name='Module')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Duplicate Rule',
                'verbose_name_plural': 'Duplicate Rules',
            },
        ),
        migrations.CreateModel(
            name='DuplicateRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(help_text='Field name to evaluate', max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, help_text='Value to compare against', max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', help_text='How to combine with next condition', max_length=10, verbose_name='Logical Operator')),
                ('order', models.IntegerField(default=0, help_text='Order of evaluation')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('duplicate_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='duplicates.duplicaterule', verbose_name='Duplicate Rule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Duplicate Rule Condition',
                'verbose_name_plural': 'Duplicate Rule Conditions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(help_text='The model this matching rule applies to', limit_choices_to=horilla.contrib.duplicates.methods.limit_content_types, on_delete=django.db.models.deletion.CASCADE, to='core.horillacontenttype', verbose_name='Module')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Matching Rule',
                'verbose_name_plural': 'Matching Rules',
            },
        ),
        migrations.AddField(
            model_name='duplicaterule',
            name='matching_rule',
            field=models.ForeignKey(help_text='The matching rule to use for detection', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_rules', to='duplicates.matchingrule', verbose_name='Matching Rule'),
        ),
        migrations.CreateModel(
            name='MatchingRuleCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field_name', models.CharField(help_text='Field name to match on', max_length=100, verbose_name='Field')),
                ('matching_method', models.CharField(choices=[('exact', 'Exact'), ('fuzzy', 'Fuzzy')], default='exact', max_length=30, verbose_name='Matching Method')),
                ('match_blank_fields', models.BooleanField(default=False, help_text='If checked, blank fields will be considered a match', verbose_name='Match Blank Fields')),
                ('order', models.IntegerField(default=0, help_text='Order of evaluation')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('matching_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='duplicates.matchingrule', verbose_name='Matching Rule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Matching Criterion',
                'verbose_name_plural': 'Matching Criteria',
                'unique_together': {('matching_rule', 'field_name')},
            },
        ),
    ]
