# Generated by Django 6.0.4 on 2026-05-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Calendar Name')),
                ('color', models.CharField(default='#E74C3C', max_length=20, verbose_name='Color')),
                ('start_date_field', models.CharField(max_length=100, verbose_name='Start Date Field')),
                ('end_date_field', models.CharField(blank=True, max_length=100, verbose_name='End Date Field')),
                ('display_name_field', models.CharField(max_length=100, verbose_name='Display Name Field')),
                ('is_selected', models.BooleanField(default=True, verbose_name='Is Selected')),
            ],
            options={
                'verbose_name': 'Custom Calendar',
                'verbose_name_plural': 'Custom Calendars',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomCalendarCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sequence')),
            ],
            options={
                'verbose_name': 'Custom Calendar Condition',
                'verbose_name_plural': 'Custom Calendar Conditions',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('credentials_json', models.JSONField(blank=True, null=True, verbose_name='Credentials JSON')),
                ('redirect_uri', models.URLField(blank=True, null=True, verbose_name='Redirect URI')),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Connected Google Account')),
                ('token', models.JSONField(blank=True, default=dict, null=True, verbose_name='OAuth Token')),
                ('oauth_state', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='OAuth State')),
                ('sync_direction', models.CharField(choices=[('horilla_to_google', 'One-way: App → Google Calendar'), ('both', 'Two-way: App ↔ Google Calendar')], default='both', max_length=20, verbose_name='Sync Direction')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('google_sync_token', models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Sync Token')),
                ('watch_channel_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Watch Channel ID')),
                ('watch_resource_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Watch Resource ID')),
                ('watch_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Watch Channel Expiration')),
                ('watch_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Watch Channel Token')),
            ],
            options={
                'verbose_name': 'Google Calendar Configuration',
                'verbose_name_plural': 'Google Calendar Configurations',
            },
        ),
        migrations.CreateModel(
            name='GoogleIntegrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_google_calendar_enabled', models.BooleanField(default=False, help_text='When enabled, users in this company can connect their Google Calendar.', verbose_name='Enable Google Calendar Integration')),
            ],
            options={
                'verbose_name': 'Google Integration Setting',
                'verbose_name_plural': 'Google Integration Settings',
            },
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('from_datetime', models.DateTimeField(verbose_name='From')),
                ('to_datetime', models.DateTimeField(verbose_name='To')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('google_event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Google Calendar Event ID')),
            ],
            options={
                'verbose_name': 'User Unavailability',
                'verbose_name_plural': 'User Unavailabilities',
                'ordering': ['-from_datetime'],
            },
        ),
        migrations.CreateModel(
            name='UserCalendarPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('calendar_type', models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('meeting', 'Meeting'), ('unavailability', 'Un Availability')], max_length=20, verbose_name='Calendar Type')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('is_selected', models.BooleanField(default=True, verbose_name='Is Selected')),
            ],
            options={
                'verbose_name': 'User Calendar Preference',
                'verbose_name_plural': 'User Calendar Preferences',
            },
        ),
    ]
