# Generated by Django 6.0.4 on 2026-05-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cadence',
                'verbose_name_plural': 'Cadences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CadenceCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Cadence Condition',
                'verbose_name_plural': 'Cadence Conditions',
            },
        ),
        migrations.CreateModel(
            name='CadenceFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('followup_number', models.PositiveSmallIntegerField(default=1, help_text='Stage number (1 = first follow-up).', verbose_name='Follow up')),
                ('followup_type', models.CharField(choices=[('task', 'Task'), ('call', 'Call'), ('email', 'Email')], max_length=20, verbose_name='Follow up Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('do_this_unit', models.CharField(choices=[('immediately', 'Immediately'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('month', 'Month')], default='immediately', max_length=20, verbose_name='Do This')),
                ('do_this_value', models.PositiveIntegerField(blank=True, help_text='Required for minute/hour/day/month.', null=True, verbose_name='Do This Value')),
                ('previous_status', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on Someone'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred'), ('overdue', 'Overdue')], help_text='Required from follow up 2 onwards.', max_length=30, null=True, verbose_name='After Previous Status Is')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('due_after_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Trigger Date + Days')),
                ('task_status', models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on Someone'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('deferred', 'Deferred')], max_length=20, null=True, verbose_name='Status')),
                ('task_priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True, verbose_name='Priority')),
                ('call_type', models.CharField(default='outbound', max_length=20, verbose_name='Call Type')),
                ('call_status', models.CharField(default='scheduled', max_length=20, verbose_name='Call Status')),
                ('call_start_after_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Call Start + Days')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Purpose')),
                ('to', models.TextField(blank=True, help_text='Recipients for this step. Choose user/email fields from the record', null=True, verbose_name='Mail to')),
            ],
            options={
                'verbose_name': 'Cadence Follow up',
                'verbose_name_plural': 'Cadence Follow ups',
                'ordering': ['followup_number', 'order', 'created_at'],
            },
        ),
    ]
