# Generated by Django 6.0.4 on 2026-05-11 07:19

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadences', '0001_initial'),
        ('core', '0001_initial'),
        ('mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cadence',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cadence',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='cadence',
            name='module',
            field=models.ForeignKey(help_text='Target module', limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('cadence_models'), on_delete=django.db.models.deletion.PROTECT, to='core.horillacontenttype', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='cadence',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='cadencecondition',
            name='cadence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='cadences.cadence', verbose_name='Cadence'),
        ),
        migrations.AddField(
            model_name='cadencecondition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cadencecondition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='cadencecondition',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='cadencefollowup',
            name='branch_from',
            field=models.ForeignKey(blank=True, help_text='Set when this step was created from a specific parent card’s + (next stage).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_children', to='cadences.cadencefollowup', verbose_name='Branched from'),
        ),
        migrations.AddField(
            model_name='cadencefollowup',
            name='cadence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='cadences.cadence', verbose_name='Cadence'),
        ),
        migrations.AddField(
            model_name='cadencefollowup',
            name='call_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadence_call_followups', to=settings.AUTH_USER_MODEL, verbose_name='Call Owner'),
        ),
        migrations.AddField(
            model_name='cadencefollowup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='cadencefollowup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='cadencefollowup',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadence_followups', to='mail.horillamailtemplate', verbose_name='Mail Template'),
        ),
        migrations.AddField(
            model_name='cadencefollowup',
            name='task_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadence_task_followups', to=settings.AUTH_USER_MODEL, verbose_name='Task Owner'),
        ),
        migrations.AddField(
            model_name='cadencefollowup',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddConstraint(
            model_name='cadencefollowup',
            constraint=models.UniqueConstraint(condition=models.Q(('followup_number', 1)), fields=('cadence',), name='unique_first_followup_per_cadence'),
        ),
        migrations.AddConstraint(
            model_name='cadencefollowup',
            constraint=models.UniqueConstraint(condition=models.Q(('followup_number__gt', 1), ('previous_status__isnull', False), ('branch_from__isnull', True)), fields=('cadence', 'followup_number', 'previous_status'), name='unique_previous_status_per_followup_bucket_unbranched'),
        ),
        migrations.AddConstraint(
            model_name='cadencefollowup',
            constraint=models.UniqueConstraint(condition=models.Q(('followup_number__gt', 1), ('previous_status__isnull', False), ('branch_from__isnull', False)), fields=('cadence', 'followup_number', 'branch_from', 'previous_status'), name='unique_previous_status_per_followup_bucket_branch'),
        ),
    ]
