# Generated by Django 6.0.4 on 2026-07-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('event', 'Event'), ('campaign', 'Campaign'), ('phone', 'Phone'), ('email', 'Email'), ('social_media', 'Social Media'), ('partner', 'Partner'), ('other', 'Other')], max_length=255, verbose_name='Account Source'),
        ),
    ]
