# Generated by Django 6.0.4 on 2026-05-11 07:19

import django.core.validators
import django.db.models.deletion
import horilla.registry.limiters
import horilla.utils.upload
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Dashboard Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dashboard_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard', to=settings.AUTH_USER_MODEL, verbose_name='Dashboard Owner')),
                ('favourited_by', models.ManyToManyField(blank=True, related_name='favourite_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Favourited By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Component Name')),
                ('component_type', models.CharField(choices=[('chart', 'Charts'), ('table_data', 'Table Data'), ('kpi', 'KPI')], max_length=50, verbose_name='Component Type')),
                ('chart_type', models.CharField(blank=True, choices=[('column', 'Column Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('funnel', 'Funnel'), ('bar', 'Bar Chart'), ('donut', 'Donut'), ('stacked_vertical', 'Stacked Vertical Chart'), ('stacked_horizontal', 'Stacked Horizontal Chart'), ('scatter', 'Scatter'), ('heatmap', 'Heat Map'), ('treemap', 'Tree Map'), ('area', 'Area Chart'), ('sankey', 'Sankey Chart'), ('radar', 'Radar Chart')], default='column', max_length=50, null=True, verbose_name='Chart Type')),
                ('metric_type', models.CharField(blank=True, default='count', max_length=100, null=True, verbose_name='Metric Type')),
                ('grouping_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grouping Field')),
                ('secondary_grouping', models.CharField(blank=True, max_length=100, null=True, verbose_name='Secondary Grouping')),
                ('y_axis_metric_type', models.CharField(blank=True, default='count', max_length=100, null=True, verbose_name='Y-axis Metric Type')),
                ('columns', models.TextField(blank=True, null=True, verbose_name='Table Columns')),
                ('sequence', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sequence')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=horilla.utils.upload.upload_path, verbose_name='KPI Icon')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('component_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to=settings.AUTH_USER_MODEL, verbose_name='Component Owner')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dashboard.dashboard', verbose_name='Dashboard')),
                ('module', models.ForeignKey(blank=True, limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('dashboard_component_models'), null=True, on_delete=django.db.models.deletion.CASCADE, to='core.horillacontenttype', verbose_name='Module')),
                ('reports', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard', to='reports.report', verbose_name='Reports')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Dashboard Component',
                'verbose_name_plural': 'Dashboard Components',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sequence')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='dashboard.dashboardcomponent', verbose_name='Component')),
            ],
            options={
                'verbose_name': 'Component Criteria',
                'verbose_name_plural': 'Component Criteria',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='DashboardFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Folder Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('favourited_by', models.ManyToManyField(blank=True, related_name='favourite_folders', to=settings.AUTH_USER_MODEL, verbose_name='Favourited By')),
                ('folder_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Folder Owner')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='dashboard.dashboardfolder', verbose_name='Folder')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Dashboard Folder',
                'verbose_name_plural': 'Dashboard Folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='dashboard.dashboardfolder', verbose_name='Folder'),
        ),
        migrations.CreateModel(
            name='DefaultHomeLayoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(blank=True, default=dict, help_text='For default home: {"kpi": ["default-kpi-0", ...], "chartsAndTables": [...]}. For dashboard: {"kpi": [id, ...], "components": [id, ...]}.')),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_layout_orders', to='dashboard.dashboard', verbose_name='Dashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Default Home Layout Order',
                'verbose_name_plural': 'Default Home Layout Orders',
                'constraints': [models.UniqueConstraint(fields=('user', 'dashboard'), name='unique_user_dashboard_layout_order'), models.UniqueConstraint(condition=models.Q(('dashboard__isnull', True)), fields=('user',), name='unique_user_default_home_layout_order')],
                'unique_together': {('user', 'dashboard')},
            },
        ),
    ]
