# Generated by Django 6.0.4 on 2026-07-03 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_horillamail_rendered_body_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horillamail',
            name='send_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_mails_by', to=settings.AUTH_USER_MODEL, verbose_name='Sent By'),
        ),
    ]
