# Generated by Django 6.0.4 on 2026-05-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(max_length=100, verbose_name='Field Name')),
                ('operator', models.CharField(choices=[('exact', 'Equals'), ('ne', 'Not Equals'), ('icontains', 'Contains'), ('not_contains', 'Does Not Contain'), ('istartswith', 'Starts With'), ('iendswith', 'Ends With'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('isnull', 'Is Empty'), ('isnotnull', 'Is Not Empty'), ('between', 'Between')], max_length=50, verbose_name='Operator')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('logical_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3, verbose_name='Logical Operator')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Automation Condition',
                'verbose_name_plural': 'Automation Conditions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('object_id', models.CharField(max_length=64, verbose_name='Object ID')),
                ('run_date', models.DateField(verbose_name='Run Date')),
                ('scheduled_for', models.DateField(blank=True, help_text='The instance date value that matched when this automation executed.', null=True, verbose_name='Scheduled For')),
            ],
            options={
                'verbose_name': 'Automation Run Log',
                'verbose_name_plural': 'Automation Run Logs',
            },
        ),
        migrations.CreateModel(
            name='HorillaAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title')),
                ('method_title', models.CharField(editable=False, max_length=100, verbose_name='Method Title')),
                ('mail_to', models.TextField(help_text="Specify recipients for email/notifications. Supports:\n- Direct email: user@example.com\n- Self: 'self' (person who triggered)\n- Instance fields: 'instance.owner.email', 'instance.created_by', 'instance.owner'\n- Multiple: comma-separated (e.g., 'self, instance.owner.email, admin@example.com')\n\nFor notifications: Use user fields directly (e.g., 'instance.owner') or email addresses.\nThe system will find users by email if an email address is provided.", verbose_name='Mail to/Notify to')),
                ('mail_detail_choice', models.TextField(default='', editable=False, verbose_name='Mail Detail Choice')),
                ('trigger', models.CharField(choices=[('on_create', 'On Create'), ('on_update', 'On Update'), ('on_create_or_update', 'Both Create and Update'), ('on_delete', 'On Delete'), ('scheduled', 'Scheduled (time-based)')], max_length=20, verbose_name='Trigger')),
                ('delivery_channel', models.CharField(choices=[('mail', 'Send as Mail'), ('notification', 'Send as Notification'), ('both', 'Send as Mail and Notification')], default='mail', max_length=50, verbose_name='Choose Delivery Channel')),
                ('schedule_date_field', models.CharField(blank=True, help_text="The date field on the record to schedule around (e.g., 'close_date', 'due_date'). Required for scheduled automations.", max_length=100, verbose_name='Target Date Field')),
                ('schedule_offset_amount', models.IntegerField(blank=True, help_text='How many days/weeks/months away from the Target Date.\nUse 0 to send on the same day.', null=True, verbose_name='Adjust By')),
                ('schedule_offset_direction', models.CharField(blank=True, choices=[('before', 'Before'), ('after', 'After')], help_text='Before = send earlier than the Target Date.\nAfter = send later than the Target Date.', max_length=10, verbose_name='Timing')),
                ('schedule_offset_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], help_text='Choose Days, Weeks, or Months.', max_length=16, verbose_name='Offset Unit')),
                ('schedule_run_time', models.TimeField(blank=True, help_text='Optional. Leave empty to run whenever the scheduler runs.', null=True, verbose_name='Run Time')),
            ],
            options={
                'verbose_name': 'Mail and Notification',
                'verbose_name_plural': 'Mail and Notifications',
            },
        ),
    ]
