# Generated by Django 6.0.4 on 2026-05-11 07:19

import django.db.models.deletion
import horilla.registry.limiters
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
        ('core', '0001_initial'),
        ('mail', '0001_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automationcondition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='automationcondition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='automationcondition',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='automationrunlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='automationrunlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horillacontenttype', verbose_name='Content Type'),
        ),
        migrations.AddField(
            model_name='automationrunlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='automationrunlog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='also_sent_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Also Send to'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='mail_server',
            field=models.ForeignKey(blank=True, help_text='Select the mail server to use for sending emails. If not selected, the primary mail server will be used.', limit_choices_to={'mail_channel': 'outgoing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.horillamailconfiguration', verbose_name='Outgoing Mail Server'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='mail_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.horillamailtemplate', verbose_name='Mail Template'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='model',
            field=models.ForeignKey(limit_choices_to=horilla.registry.limiters.ContentTypeLimiter('automation_models'), on_delete=django.db.models.deletion.CASCADE, to='core.horillacontenttype', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate', verbose_name='Notification Template'),
        ),
        migrations.AddField(
            model_name='horillaautomation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='automationrunlog',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='automations.horillaautomation', verbose_name='Automation'),
        ),
        migrations.AddField(
            model_name='automationcondition',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automations.horillaautomation', verbose_name='Automation'),
        ),
        migrations.AlterUniqueTogether(
            name='automationrunlog',
            unique_together={('automation', 'content_type', 'object_id', 'scheduled_for')},
        ),
    ]
